feature_list_Desktop_KIT_1 = [
    "ir",
    "ot",
    "ve",
    "no",
    "ha",
    "he",
    "to",
    "rd",
    "hSPACE",
    "is",
    "co",
    "un",
    "pSPACE",
    "di",
    "fi",
    "ni",
    "pl",
    "ne",
    "fSPACE",
    "hi",
    "tSPACE",
    "es",
    "eSPACE",
    "on",
    "dSPACE",
    "oSPACE",
    "rl",
    "me",
    "le",
    "wi",
    "if",
    "nc",
    "lSPACE",
    "SPACEs",
    "SPACEa",
    "nt",
    "pe",
    "or",
    "iSPACE",
    "wo",
    "SPACEt",
    "ca",
    "nd",
    "ce",
    "ly",
    "ov",
    "te",
    "ed",
    "th",
    "tw",
    "ff",
    "in",
    "aSPACE",
    "SPACEl",
    "li",
    "se",
    "it",
    "la",
    "SPACEn",
    "of",
    "ul",
    "ec",
    "ct",
    "yp",
    "et",
    "SPACEc",
    "io",
    "sa",
    "ts",
    "re",
    "SPACEf",
    "ti",
    "il",
    "ap",
    "ue",
    "ySPACE",
    "ds",
    "SPACEh",
    "el",
    "da",
    "SPACEo",
    "ol",
    "ll",
    "ef",
    "SPACEp",
    "ta",
    "st",
    "am",
    "SPACEw",
    "ar",
    "rs",
    "en",
    "er",
    "sSPACE",
    "qu",
    "s.",
    "at",
    ".SPACE",
    "nSPACE",
    "SPACEu",
    "SPACEm",
    "as",
    "SPACEi",
    "e.",
    "SPACEd",
    "si",
    "ee",
    "ss",
]

feature_list_Desktop_KIT_2 = [
    "rd",
    "rl",
    "to",
    "un",
    "ap",
    "ot",
    "el",
    "ol",
    "ir",
    "ef",
    "rs",
    "ov",
    "yp",
    "ly",
    "nSPACE",
    "SPACEm",
    "ue",
    "if",
    "no",
    "nt",
    "ve",
    "ed",
    "SPACEs",
    "iSPACE",
    "es",
    "co",
    "ee",
    "SPACEn",
    "wi",
    "st",
    "ni",
    "it",
    "ct",
    "nc",
    "et",
    "hi",
    "ce",
    "pSPACE",
    "oSPACE",
    "hSPACE",
    "SPACEf",
    "pe",
    "sa",
    "se",
    "re",
    "of",
    "ts",
    "SPACEu",
    "di",
    "la",
    "ff",
    "si",
    "aSPACE",
    "ta",
    "ti",
    "en",
    "ySPACE",
    "pl",
    "ss",
    "da",
    "fSPACE",
    "li",
    "tw",
    "lSPACE",
    "th",
    "SPACEc",
    "il",
    "ne",
    "is",
    "te",
    "or",
    "le",
    "ul",
    "SPACEp",
    "as",
    "SPACEl",
    "s.",
    ".SPACE",
    "in",
    "me",
    "ds",
    "dSPACE",
    "SPACEa",
    "er",
    "nd",
    "SPACEt",
    "fi",
    "he",
    "ha",
    "qu",
    "ll",
    "ec",
    "am",
    "SPACEd",
    "on",
    "ca",
    "at",
    "sSPACE",
    "SPACEi",
    "SPACEo",
    "wo",
    "tSPACE",
    "SPACEh",
    "io",
    "eSPACE",
    "e.",
    "SPACEw",
    "ar",
]

feature_list_Desktop_KIT_3 = [
    "un",
    "to",
    "li",
    "rl",
    "es",
    "nt",
    "ce",
    "hSPACE",
    "th",
    "iSPACE",
    "rd",
    "fi",
    "fSPACE",
    "el",
    "pl",
    "si",
    "ef",
    "en",
    "ff",
    "SPACEs",
    "oSPACE",
    "ed",
    "co",
    "ov",
    "ap",
    "ni",
    "if",
    "dSPACE",
    "il",
    "ll",
    "SPACEn",
    "sa",
    "ds",
    "ot",
    "as",
    "ir",
    "et",
    "pSPACE",
    "SPACEc",
    "tw",
    "ca",
    "ve",
    "he",
    "it",
    "lSPACE",
    "SPACEt",
    "ar",
    "SPACEf",
    "in",
    "ue",
    "am",
    "ct",
    "la",
    "no",
    "wi",
    "nSPACE",
    "ti",
    "ne",
    "ec",
    "SPACEp",
    "ta",
    "is",
    "st",
    "rs",
    "pe",
    "ss",
    "or",
    "re",
    "hi",
    "io",
    "ts",
    "SPACEw",
    "se",
    "aSPACE",
    "ySPACE",
    "ha",
    "nc",
    "ol",
    "da",
    "of",
    "SPACEu",
    "le",
    "ly",
    "SPACEm",
    "SPACEl",
    "on",
    "at",
    "s.",
    "sSPACE",
    "yp",
    "di",
    "SPACEa",
    "te",
    "ee",
    "SPACEd",
    "eSPACE",
    "er",
    "SPACEi",
    "ul",
    ".SPACE",
    "me",
    "qu",
    "e.",
    "SPACEo",
    "wo",
    "SPACEh",
    "nd",
    "tSPACE",
]

feature_list_Desktop_KIT_4 = [
    "un",
    "pl",
    "rl",
    "rd",
    "ol",
    "in",
    "as",
    "ds",
    "en",
    "me",
    "ef",
    "to",
    "iSPACE",
    "ll",
    "ir",
    "nt",
    "fSPACE",
    "ot",
    "at",
    "ar",
    "ee",
    "if",
    "am",
    "fi",
    "el",
    "SPACEm",
    "co",
    "ed",
    "ap",
    "SPACEu",
    "di",
    "aSPACE",
    "hSPACE",
    "ly",
    "hi",
    "ov",
    "it",
    "SPACEn",
    "ct",
    "SPACEi",
    "ff",
    "ca",
    "tw",
    "ce",
    "SPACEf",
    "es",
    "wo",
    "ni",
    "si",
    "eSPACE",
    "et",
    "ti",
    "th",
    "nc",
    "ySPACE",
    "da",
    "SPACEs",
    "qu",
    "pe",
    "er",
    "SPACEl",
    "or",
    "oSPACE",
    "nSPACE",
    "li",
    "SPACEc",
    "ul",
    "pSPACE",
    "st",
    "of",
    "il",
    "wi",
    "on",
    "SPACEp",
    "la",
    "yp",
    "s.",
    "SPACEt",
    "sSPACE",
    "rs",
    "dSPACE",
    "he",
    "sa",
    "ec",
    "te",
    "lSPACE",
    "ta",
    "ha",
    "SPACEw",
    "nd",
    "ss",
    "ue",
    "ts",
    "no",
    "ne",
    "ve",
    "io",
    "is",
    "SPACEd",
    ".SPACE",
    "SPACEa",
    "e.",
    "SPACEo",
    "se",
    "SPACEh",
    "tSPACE",
    "le",
    "re",
]
feature_list_Desktop_KHT = [
    "v",
    "n",
    "s",
    "h",
    "BACKSPACE",
    "r",
    "u",
    "m",
    "i",
    "p",
    "t",
    "d",
    "o",
    "SPACE",
    "l",
    "q",
    "e",
    ".",
    "c",
    "w",
    "f",
    "a",
]

feature_dict_advanced_word_Desktop = {
    "if": [2, 1, 3, 4, 6, 0, 13, 15, 10, 12, 7, 9],
    "this": [6, 1, 3, 2, 8, 10, 4, 5, 12, 13, 15, 0, 7, 9, 14, 11],
    "have": [6, 13, 3, 1, 0, 7, 4, 8, 15, 5, 12, 10, 9, 14, 2, 11],
    "me": [4, 6, 0, 13, 15, 2, 7, 9, 10, 12, 1, 3],
    "with": [6, 13, 9, 0, 12, 4, 10, 15, 7, 1, 5, 11, 8, 2, 14, 3],
    "to": [4, 6, 0, 13, 15, 10, 12, 7, 9, 1, 3, 2],
    "sentences": [13, 6, 5, 8, 11, 14, 3, 4, 10, 0, 1, 7, 15, 2, 12, 9],
    "not": [1, 2, 3, 4, 6, 10, 12, 13, 15, 8, 11, 0, 7, 9, 5, 14],
    "type": [1, 3, 11, 13, 5, 14, 4, 10, 2, 8, 12, 7, 0, 6, 15, 9],
    "words": [11, 14, 8, 5, 1, 6, 9, 4, 13, 15, 3, 7, 0, 12, 10, 2],
    "will": [1, 11, 5, 3, 15, 2, 13, 14, 12, 4, 9, 10, 8, 0, 6, 7],
    "carefully": [1, 4, 3, 10, 0, 15, 14, 7, 13, 5, 8, 11, 9, 12, 6, 2],
    "different": [6, 3, 8, 15, 9, 1, 12, 5, 14, 4, 11, 7, 13, 10, 0, 2],
    "two": [1, 14, 11, 3, 8, 5, 13, 15, 7, 9, 10, 12, 4, 6, 0, 2],
    "see": [14, 8, 13, 15, 3, 0, 1, 10, 12, 5, 7, 9, 4, 6, 2, 11],
    "first": [1, 5, 8, 14, 6, 4, 10, 3, 0, 15, 12, 7, 2, 9, 13, 11],
    "sample": [4, 5, 8, 1, 14, 13, 15, 10, 3, 0, 11, 2, 7, 6, 12, 9],
    "sets": [6, 3, 1, 9, 10, 12, 7, 5, 4, 13, 8, 15, 0, 11, 14, 2],
    "that": [6, 1, 3, 7, 0, 8, 10, 2, 9, 14, 5, 12, 4, 13, 15, 11],
    "overlap": [1, 10, 14, 15, 6, 3, 8, 9, 11, 2, 0, 7, 5, 13, 12, 4],
    "collection": [15, 6, 10, 1, 12, 14, 7, 8, 13, 4, 11, 0, 9, 3, 5, 2],
    "is": [4, 6, 2, 10, 12, 1, 3, 7, 9, 0, 13, 15],
    "there": [1, 3, 2, 6, 4, 8, 5, 11, 15, 10, 14, 7, 9, 13, 0, 12],
    "data": [1, 3, 8, 2, 4, 5, 7, 9, 13, 0, 6, 10, 11, 12, 15, 14],
    "of": [1, 3, 4, 6, 10, 12, 0, 13, 15, 7, 9, 2],
    "test": [13, 11, 0, 14, 15, 5, 3, 1, 7, 4, 8, 6, 2, 10, 12, 9],
    "are": [2, 5, 13, 15, 4, 6, 8, 3, 10, 12, 0, 11, 1, 14, 7, 9],
    "lines": [6, 11, 5, 15, 4, 13, 10, 3, 8, 14, 12, 1, 0, 9, 2, 7],
    "the": [1, 4, 6, 2, 8, 10, 12, 7, 9, 3, 13, 15, 0, 11, 5, 14],
    "in": [1, 3, 4, 6, 0, 13, 15, 7, 9, 10, 12, 2],
    "selected": [13, 0, 15, 5, 1, 6, 9, 3, 14, 12, 10, 8, 7, 11, 4, 2],
    "a": [0, 1, 3],
    "i": [0, 1, 3],
}
top_feature_advanced_word_Desktop_map = {}
top_feature_advanced_word_Desktop_map["selected"] = [0, 7, 10]
top_feature_advanced_word_Desktop_map["me"] = [4, 6]
top_feature_advanced_word_Desktop_map["if"] = [4, 6]
top_feature_advanced_word_Desktop_map["that"] = [4]
top_feature_advanced_word_Desktop_map["sample"] = [4]
top_feature_advanced_word_Desktop_map["test"] = [4]
top_feature_advanced_word_Desktop_map["have"] = [4]
top_feature_advanced_word_Desktop_map["data"] = [1, 4]
top_feature_advanced_word_Desktop_map["with"] = [13]
top_feature_advanced_word_Desktop_map["will"] = [13]

top_feature_advanced_word_Desktop_only_map = {}
top_feature_advanced_word_Desktop_only_map["if"] = [2, 1, 3, 4, 6, 0, 13]
top_feature_advanced_word_Desktop_only_map["this"] = [6, 1, 3]
top_feature_advanced_word_Desktop_only_map["have"] = [6]
top_feature_advanced_word_Desktop_only_map["me"] = [4, 6]
top_feature_advanced_word_Desktop_only_map["with"] = [6]
top_feature_advanced_word_Desktop_only_map["to"] = [4, 6]
top_feature_advanced_word_Desktop_only_map["sentences"] = [13, 6]
top_feature_advanced_word_Desktop_only_map["not"] = [1]
top_feature_advanced_word_Desktop_only_map["type"] = [1]
top_feature_advanced_word_Desktop_only_map["words"] = [11, 8, 14]
top_feature_advanced_word_Desktop_only_map["will"] = [1]
top_feature_advanced_word_Desktop_only_map["carefully"] = [1]
# utilities to get the most commonly occurring words and corresponding features for all users
word_feature_id_mapping = {
    1: "wht",
    2: "avg_kht",
    3: "std_kht",
    4: "median_kht",
    5: "avg_f1",
    6: "std_f1",
    7: "median_f1",
    8: "avg_f2",
    9: "std_f2",
    10: "median_f2",
    11: "avg_f3",
    12: "std_f3",
    13: "median_f3",
    14: "avg_f4",
    15: "std_f4",
    16: "median_f4",
}
top_feature_KIT_Desktop_F1 = [
    "in",
    "nSPACE",
    "et",
    "lSPACE",
    "oSPACE",
    "ca",
    "iSPACE",
    "pl",
    "ve",
    "ha",
    "ne",
    "da",
    "he",
    "wi",
]
top_feature_KIT_Tablet_F1 = ["me", "is", "ne", "ha"]
top_feature_KIT_Tablet_F2 = ["ha", "is", "me"]
top_feature_KIT_Tablet_F3 = ["ne"]
top_feature_KIT_Phone_F1 = ["BACKSPACEBACKSPACE"]
top_feature_KIT_Phone_F2 = ["BACKSPACEBACKSPACE"]
top_feature_KIT_Phone_F4 = ["BACKSPACEBACKSPACE"]
